export default function icons(){
 return [
    {
      name: "icon-basket",
      classtype:"fas",
      class:"fa-basketball-ball"
    },
    {
      name:"icon-battery",
      classtype:"fas",
      class:"fa-battery-full"
    },
    {
      name: "icon-bone",
      classtype:"fas",
      class:"fa-bone"
    },
    {
      name: "icon-bolt",
      classtype:"fas",
      class:"fa-bolt"
    },
    {
      name:"icon-box",
      classtype:"fas",
      class:"fa-box"
    },

    {
      name:"android",
      classtype:"fab",
      class:"fa-android"
    },
    {
      name:"icon-chart-pie",
      classtype:"fas",
      class:"fa-chart-pie"
    },
    {
      name:"chess-king",
      classtype:"fas",
      class:"fa-chess-king"
    },
    {
      name:"icon-balance-scale",
      classtype:"fas",
      class:"fa-balance-scale"
    },
    {
      name:"icon-html5",
      classtype:"fab",
      class:"fa-html5"
    },
    {
      name:"css3",
      classtype:"fab",
      class:"fa-css3-alt"
    },
    {
      name:"icon-js",
      classtype:"fab",
      class:"fa-js-square"
    },
    {
      name:"icon-nodejs",
      classtype:"fab",
      class:"fa-node-js"
    },
    {
      name:"icon-apple",
      classtype:"fab",
      class:"fa-apple"
    },
    {
      name:"icon-barcode",
      classtype:"fas",
      class:"fa-barcode"
    },
    {
      name:"icon-book",
      classtype:"fas",
      class:"fa-book"
    },
    {
      name:"icon-heart",
      classtype:"fas",
      class:"fa-heart"
    },
    {
      name:"icon-camera-retro",
      classtype:"fas",
      class:"fa-camera-retro"
    },
    {
      name:"icon",
      classtype:"fas",
      class:"fa-cat"
    }
  ]
} 